/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controlador.Controlador;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Adán
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private Controlador con;
    private List<File> unidades;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setTitle("Limpieza de discos");
        con = new Controlador();
        try  {
            unidades = new ArrayList<>(Arrays.asList(con.listarUnidadesByMario()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "el SO no es completamente "
                    + "compatible, elije una carpeta para poder usar el progarama");
            JFileChooser jf = new JFileChooser();
            jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int seleccion = jf.showOpenDialog(this);
            if(seleccion==JFileChooser.APPROVE_OPTION){
                unidades.add(jf.getSelectedFile());
                unidad.addItem(jf.getSelectedFile().getName());
            }
            else
                dispose();
        }
        List<String> nombreUnidades = new ArrayList<>();
        unidades.forEach((file) -> nombreUnidades.add(File.separator+file.getName()));
        this.unidad.setModel(new DefaultComboBoxModel(nombreUnidades.toArray()));
        this.setIconImage(new ImageIcon(getClass().getResource("/images/floppy.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        botonGrandes = new javax.swing.JButton();
        botonSeguro = new javax.swing.JButton();
        botonDuplicados = new javax.swing.JButton();
        botonCarpetasVacias = new javax.swing.JButton();
        botonEspacioLibre = new javax.swing.JButton();
        unidad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Limpieza de disco");

        botonGrandes.setText("Borrar de gran tamaño");
        botonGrandes.setName("tamanio"); // NOI18N
        botonGrandes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSeguroMouseEntered(evt);
            }
        });
        botonGrandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrandesActionPerformed(evt);
            }
        });

        botonSeguro.setText("Borrado seguro");
        botonSeguro.setName("seguro"); // NOI18N
        botonSeguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSeguroMouseEntered(evt);
            }
        });
        botonSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguroActionPerformed(evt);
            }
        });

        botonDuplicados.setText("Borrar duplicados");
        botonDuplicados.setName("duplicados"); // NOI18N
        botonDuplicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSeguroMouseEntered(evt);
            }
        });
        botonDuplicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDuplicadosActionPerformed(evt);
            }
        });

        botonCarpetasVacias.setText("Borrar carpetas vacías");
        botonCarpetasVacias.setName("vacias"); // NOI18N
        botonCarpetasVacias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSeguroMouseEntered(evt);
            }
        });
        botonCarpetasVacias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarpetasVaciasActionPerformed(evt);
            }
        });

        botonEspacioLibre.setText("Espacio libre");
        botonEspacioLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEspacioLibreActionPerformed(evt);
            }
        });

        unidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Unidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEspacioLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonGrandes)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonDuplicados))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(263, 263, 263)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18)
                                .addComponent(botonCarpetasVacias))
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEspacioLibre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGrandes)
                    .addComponent(botonSeguro)
                    .addComponent(botonDuplicados)
                    .addComponent(botonCarpetasVacias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEspacioLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEspacioLibreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, " Hay un total de " 
                +con.espacioLibreFormateado(this.unidades.get(this.unidad.getSelectedIndex()))
                + " libres", "Espacio libre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonEspacioLibreActionPerformed

    private void botonCarpetasVaciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarpetasVaciasActionPerformed
        // TODO add your handling code here:
        File index = this.unidades.get(this.unidad.getSelectedIndex());
        int opcionPanel = JOptionPane.showConfirmDialog(this,
                "¿quieres borrar carpetas vacias?", "Borrado de carpetas",
                JOptionPane.YES_NO_OPTION);
        if (opcionPanel == JOptionPane.YES_OPTION) {
            this.descripcion.setText("Espere...esto puede tardar bastante");
            int contador = con.borrarDirectoriosVacios(index.getAbsolutePath());
            if (contador > 0) {
                JOptionPane.showMessageDialog(this, "se han eliminado " + contador
                        + " carpetas vacías", "Borrado de carpetas",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna"
                        + " carpeta vacía", "Borrado de carpetas",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_botonCarpetasVaciasActionPerformed

    private void botonGrandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrandesActionPerformed
        // TODO add your handling code here:
        Integer[] lanzar = new Integer[] {1,2,5,10};
        int seleccion = JOptionPane.showOptionDialog(this, "¿De cuantos gigas?"
                , "borrado de archivos grandes", JOptionPane.YES_NO_OPTION ,
                JOptionPane.QUESTION_MESSAGE,null, lanzar, "1");
        
        if(seleccion!=-1){
            JOptionPane.showMessageDialog(this, "esto puede tardar...");
            File archivo = this.unidades.get(this.unidad.getSelectedIndex());
            List<File> listarDirectoriosTamanio = con.listarDirectoriosTamanio(archivo,lanzar[seleccion]);
            new PantallaBorrado(this, true, con, listarDirectoriosTamanio).setVisible(true);
        }
        
        
    }//GEN-LAST:event_botonGrandesActionPerformed

    private void botonDuplicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDuplicadosActionPerformed
        // TODO add your handling code here:
        Map<File,File> duplicados = new HashMap<>();
        File ficheroBusqueda=null;
        JFileChooser jf = new JFileChooser(this.unidades.get(this.unidad.getSelectedIndex()));
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //preguntar si quiere comprobar de carpetas en concreto.
        int seleccion = JOptionPane.showConfirmDialog(this, "¿Quiere comprobar solo de una carpeta especifica?,"
                + " sino este proceso podria tardar horas", "comprobar iguales"
                , JOptionPane.YES_NO_CANCEL_OPTION);
        if(seleccion==JOptionPane.YES_OPTION){
            int seleccionFile = jf.showOpenDialog(this);
            if (seleccionFile==JFileChooser.APPROVE_OPTION) 
                    ficheroBusqueda=jf.getSelectedFile();
        }else if (seleccion == JOptionPane.NO_OPTION)
            ficheroBusqueda= this.unidades.get(this.unidad.getSelectedIndex());
        
        if(ficheroBusqueda!=null){
            
            try {
                JOptionPane.showMessageDialog(this, "esto puede tardar...");
                con.comprobarIgualesCarpeta(ficheroBusqueda,duplicados);
            } catch (IOException ex){}
            if(!duplicados.isEmpty())
            new PantallaDuplicados(this, true,duplicados,con).setVisible(true);
            else
                JOptionPane.showMessageDialog(this,"no se ha encontrado ningun archivo similar");
        }
    }//GEN-LAST:event_botonDuplicadosActionPerformed

    private void botonSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguroActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser(this.unidades.get(this.unidad.getSelectedIndex()));
        jf.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int seleccion = jf.showOpenDialog(this);
        if(seleccion==JFileChooser.APPROVE_OPTION){
            JOptionPane.showMessageDialog(this, "esto puede tardar...");
            int borrados = 0;
            try {
                borrados = con.borradoSeguro(jf.getSelectedFile());
            } catch (IOException ex) {
                Logger.getLogger(PantallaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("se han borrado "+borrados);
        }
    }//GEN-LAST:event_botonSeguroActionPerformed

    private void botonSeguroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSeguroMouseEntered
        // TODO add your handling code here:
        String cabecerahtml = "<html><head></head><body> ";
        String finalhtml= "</body></html>";
        switch (evt.getComponent().getName().toLowerCase()) {
            case "tamanio":
                this.descripcion.setText(
                        cabecerahtml+"busca archivos con un tamaño igual o superior a 1, 2, 5 o 10 gb en el disco"
                                + " te muestra los archivos para poder eliminarlos"+finalhtml);
                break;
            case "vacias":
                this.descripcion.setText(
                        cabecerahtml+"elimina todas las carpetas vacias en el disco seleccionado"+finalhtml);
                break;
            case "seguro":
                this.descripcion.setText(
                cabecerahtml+"permite borrar una carpeta (o archivo) de manera segura,"
                        + " haciendo que sea mas difícil de recuperar con "
                        + "programas de recuperación"+finalhtml);
                break;
            case "duplicados":
                this.descripcion.setText(
                cabecerahtml+"busca en el disco selecciona (o carpeta) archivos similares"
                        + " y te los muestra en una tabla para poder borrarlos <br>"
                        + "<b style=\"color:red;\">aviso: este proceso puede durar horas</b>"+finalhtml);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_botonSeguroMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarpetasVacias;
    private javax.swing.JButton botonDuplicados;
    private javax.swing.JButton botonEspacioLibre;
    private javax.swing.JButton botonGrandes;
    private javax.swing.JButton botonSeguro;
    private javax.swing.JLabel descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JComboBox<String> unidad;
    // End of variables declaration//GEN-END:variables
}
