/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Controlador.Controlador;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumnop
 */
public class PantallaDuplicados extends javax.swing.JDialog {

    Map<File, File> mapa;
    Controlador con;
    List<File> ficherosDuplicados;
    Informacion inf;

    /**
     * Creates new form PantallaDuplicados
     */
    public PantallaDuplicados(java.awt.Frame parent, boolean modal, Map<File, File> mapa, Controlador con) {
        super(parent, modal);
        initComponents();
        this.mapa = mapa;
        this.rellenarLista();
        this.con = con;
        this.ficherosDuplicados = new ArrayList<>();
        mapa.keySet().forEach((value) -> {
            ficherosDuplicados.add(value);
        });
        tabla.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        comprobacionBoton = new javax.swing.JButton();
        borrarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Archivos duplicados");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaMouseMoved(evt);
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tablaMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        comprobacionBoton.setText("<html><body><p>Comprobacion</p></br><p>intensiva</p></body></html>");
        comprobacionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobacionBotonActionPerformed(evt);
            }
        });

        borrarBoton.setText("<html><body><p>Borrar</p></br><p>archivos</p></body></html>");
        borrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comprobacionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comprobacionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprobacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobacionBotonActionPerformed
        try {
            // TODO add your handling code here:
            this.mapa = con.comprobarIgualesMap(mapa);
        } catch (IOException ex) {
            Logger.getLogger(PantallaDuplicados.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.rellenarLista();
    }//GEN-LAST:event_comprobacionBotonActionPerformed

    private void borrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBotonActionPerformed
        // TODO add your handling code here:
        if (tabla.getSelectedRows().length == 0) {
            JOptionPane.showMessageDialog(this, "no has seleccionado nada");
        } else {
            List<File> ficherosBorrar = new ArrayList<>();
            for (int selectedRow : tabla.getSelectedRows()) {
                File fichero = this.ficherosDuplicados.get(selectedRow);
                this.mapa.remove(fichero);
                ficherosBorrar.add(fichero);
            }
            con.borrarArchivos(ficherosBorrar);

            JOptionPane.showMessageDialog(this, "se han borrado " + ficherosBorrar.size() + " archivos");
            this.rellenarLista();
        }
    }//GEN-LAST:event_borrarBotonActionPerformed

    private void tablaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseMoved
        // TODO add your handling code here:
        if (this.inf == null) {

            this.inf = new Informacion(this, false, this.ficherosDuplicados.get(0));
            this.inf.setLocation(new Point(evt.getXOnScreen(), evt.getYOnScreen()));
            this.inf.setVisible(true);
        }
    }//GEN-LAST:event_tablaMouseMoved

    private void tablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseExited
        // TODO add your handling code here:
        if(this.inf!=null)
        this.inf.dispose();
        this.inf=null;
    }//GEN-LAST:event_tablaMouseExited

    public void rellenarLista() {
        String[] columnas = {"archivo original", "archivo duplicado"};
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        String[] fila = new String[2];
        for (File columna : this.mapa.keySet()) {
            fila[0] = this.mapa.get(columna).getName();
            fila[1] = columna.getName();
            dtm.addRow(fila);
        }
        
        this.tabla.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBoton;
    private javax.swing.JButton comprobacionBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
